---
- hosts: webservers
  gather_facts: yes
  become: yes # Use sudo for privilege escalation

  tasks:
    - name: Uninstall Node.js (if already installed)
      apt:
        name: nodejs
        state: absent
      when: ansible_os_family == 'Debian'

    - name: Remove Node.js repository (Debian/Ubuntu)
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }} main"
        state: absent
        filename: nodesource
      when: ansible_os_family == 'Debian'

    - name: Install Node.js
      apt:
        name: nodejs
        state: present
      when: ansible_os_family == 'Debian'
